"use client";
import {useEffect,useMemo,useState} from "react";
import {BarChart3,CheckCircle2,Clock3,Database,MapPin,RefreshCw,Search,ShieldCheck,Vote} from "lucide-react";
import CearaMap from "@/components/CearaMap";
type Row={section:string;location:string;municipality:string;votes:number;eligible:number;ibgeCode?:string};
type Payload={rows:Row[];updatedAt:string;source:"sheet"|"demo";message?:string};
const initial:Payload={rows:[],updatedAt:new Date().toISOString(),source:"demo"};
const fmt=new Intl.NumberFormat("pt-BR");
export default function Home(){
 const[mode,setMode]=useState<"interno"|"tse">("interno"),[city,setCity]=useState("Todos os municípios"),[query,setQuery]=useState(""),[data,setData]=useState<Payload>(initial),[loading,setLoading]=useState(false);
 async function refresh(){setLoading(true);try{const r=await fetch(mode==="interno"?"/api/dashboard":"/api/tse",{cache:"no-store"});setData(await r.json())}finally{setLoading(false)}}
 useEffect(()=>{void refresh();const id=setInterval(refresh,60000);return()=>clearInterval(id)},[mode]);
 const cities=useMemo(()=>["Todos os municípios",...Array.from(new Set(data.rows.map(r=>r.municipality))).sort()], [data.rows]);
 const rows=useMemo(()=>data.rows.filter(r=>(city==="Todos os municípios"||r.municipality===city)&&(`${r.section} ${r.location}`).toLowerCase().includes(query.toLowerCase())),[data.rows,city,query]);
 const votes=rows.reduce((s,r)=>s+r.votes,0),eligible=rows.reduce((s,r)=>s+r.eligible,0),sections=rows.filter(r=>r.votes>0).length,totalSections=mode==="interno"?161:Math.max(data.rows.length,1),progress=Math.min(100,sections/totalSections*100);
 const previousElection=18738,achievement=Math.min(100,votes/previousElection*100),difference=votes-previousElection,projectedVotes=progress>0?Math.round(votes/(progress/100)):0;
 const ranking=Object.entries(rows.reduce<Record<string,number>>((a,r)=>{a[r.location]=(a[r.location]||0)+r.votes;return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,5);
 return <main className="app-shell">
  <header className="topbar"><div className="brand"><span className="brand-mark">40</span><div><strong>APURAÇÃO 2026</strong><small>Sérgio Aguiar · Deputado Estadual</small></div></div><div className="status"><i/>Atualização automática<button onClick={refresh}><RefreshCw className={loading?"spin":""}/></button></div></header>
  <section className="toolbar"><div className="switch"><button className={mode==="interno"?"active":""} onClick={()=>setMode("interno")}><Database/>Apuração interna</button><button className={mode==="tse"?"active":""} onClick={()=>setMode("tse")}><ShieldCheck/>TSE oficial</button></div><label><MapPin/><select value={city} onChange={e=>setCity(e.target.value)}>{cities.map(c=><option key={c}>{c}</option>)}</select></label><button className="refresh" onClick={refresh}><RefreshCw/>Atualizar dados</button></section>
  {data.source==="demo"&&<div className="notice"><Clock3/><span><strong>Integração pronta para configurar.</strong> Os votos aparecerão assim que a URL de leitura for informada.</span></div>}
  <section className="hero">
   <article className="panel map-panel"><div className="heading"><div><span>CEARÁ · 184 MUNICÍPIOS</span><h1>Mapa da apuração</h1></div><a className="sheet-link" href="https://docs.google.com/spreadsheets/d/1tKxRQp6gE-fiObtn5HVPg8ewFVgZOVp7jr3Bhh3qhYY/edit" target="_blank">Abrir planilha de entrada</a></div><div className="map-stage"><CearaMap rows={data.rows} selected={city} onSelect={setCity}/></div></article>
   <article className="panel summary"><div className="candidate"><b>40<span>888</span></b><div><span>DEPUTADO ESTADUAL</span><h2>Sérgio Aguiar</h2><small>Resultado selecionado · Ceará</small></div></div><div className="total"><span>Total de votos</span><strong>{fmt.format(votes)}</strong><small>{mode==="tse"?"Fonte: resultados oficiais do TSE":"Fonte: planilha de apuração interna"}</small></div><div className="progress-label"><span>Urnas/seções com resultado</span><b>{sections} de {totalSections}</b></div><div className="progress"><i style={{width:`${progress}%`}}/></div><small>{progress.toFixed(2).replace(".",",")}% apurado</small><div className="projection-card"><div className="projection-title"><BarChart3/><span>PROJEÇÃO DE VOTOS</span></div><div className="projection-grid"><div><small>Última eleição</small><b>{fmt.format(previousElection)}</b></div><div><small>Projeção atual</small><b>{projectedVotes?fmt.format(projectedVotes):"—"}</b></div><div><small>Diferença</small><b className={difference>=0?"positive":"negative"}>{difference>=0?"+":""}{fmt.format(difference)}</b></div><div><small>Meta atingida</small><b>{achievement.toFixed(1).replace(".",",")}%</b></div></div><div className="projection-progress"><i style={{width:`${achievement}%`}}/></div></div><div className="metrics"><div><Vote/><span>Votos</span><b>{fmt.format(votes)}</b></div><div><CheckCircle2/><span>Aptos listados</span><b>{fmt.format(eligible)}</b></div><div><BarChart3/><span>Municípios</span><b>{new Set(rows.map(r=>r.municipality)).size}</b></div></div><div className="updated">Atualizado em {new Date(data.updatedAt).toLocaleString("pt-BR")}</div></article>
  </section>
  <section className="details"><article className="panel ranking"><div className="heading"><div><span>DESTAQUES</span><h3>Locais com mais votos</h3></div><BarChart3/></div>{ranking.filter(x=>x[1]>0).map(([n,v],i)=><div className="rank" key={n}><b>{i+1}</b><span>{n}</span><strong>{fmt.format(v)}</strong></div>)}{!ranking.some(x=>x[1]>0)&&<p className="empty">Os totais aparecerão conforme os dados forem inseridos.</p>}</article><article className="panel table-card"><div className="heading"><div><span>DETALHAMENTO</span><h3>Resultados por seção</h3></div><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar seção ou local"/></label></div><div className="table-scroll"><table><thead><tr><th>Seção</th><th>Local</th><th>Município</th><th>Votos</th></tr></thead><tbody>{rows.map(r=><tr key={r.municipality+r.section}><td>{r.section}</td><td>{r.location}</td><td>{r.municipality}</td><td><b>{fmt.format(r.votes)}</b></td></tr>)}</tbody></table></div></article></section>
  <footer><span>Painel eleitoral · Dados sujeitos à conferência</span><span>Desenvolvido por <b>Álefim Oliveira</b></span></footer>
 </main>
}
