"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {BarChart3,CheckCircle2,Clock3,Database,MapPin,PartyPopper,RefreshCw,Search,ShieldCheck,Volume2,Vote} from "lucide-react";
import CearaMap from "@/components/CearaMap";
type Row={section:string;location:string;municipality:string;votes:number;federalVotes?:number;checked?:boolean;candidateVotes?:Record<string,number>;eligible:number;ibgeCode?:string};
type Payload={rows:Row[];updatedAt:string;source:"sheet"|"demo";message?:string;federalCandidate?:string;candidateMeta?:{key:string;name:string;number:string;office:string}[]};
const initial:Payload={rows:[],updatedAt:new Date().toISOString(),source:"demo"};
const fmt=new Intl.NumberFormat("pt-BR");
const PREVIOUS_ELECTION_VOTES=18738;
const VICTORY_VIDEO_ID="Sa-DrZH1nsw";
export default function Home(){
 const[mode,setMode]=useState<"interno"|"tse">("interno"),[city,setCity]=useState("Todos os municípios"),[query,setQuery]=useState(""),[data,setData]=useState<Payload>(initial),[loading,setLoading]=useState(false),[soundArmed,setSoundArmed]=useState(false),[playerReady,setPlayerReady]=useState(false);
 const playerRef=useRef<HTMLIFrameElement>(null);
 const sendPlayerCommand=(func:string,args:unknown[]=[])=>playerRef.current?.contentWindow?.postMessage(JSON.stringify({event:"command",func,args}),"*");
 async function refresh(){setLoading(true);try{const r=await fetch(mode==="interno"?"/api/dashboard":"/api/tse",{cache:"no-store"});setData(await r.json())}finally{setLoading(false)}}
 useEffect(()=>{void refresh();const id=setInterval(refresh,5000);return()=>clearInterval(id)},[mode]);
 const cities=useMemo(()=>["Todos os municípios",...Array.from(new Set(data.rows.map(r=>r.municipality))).sort()], [data.rows]);
 const rows=useMemo(()=>data.rows.filter(r=>(city==="Todos os municípios"||r.municipality===city)&&(`${r.section} ${r.location}`).toLowerCase().includes(query.toLowerCase())),[data.rows,city,query]);
 const votes=rows.reduce((s,r)=>s+r.votes,0),federalVotes=rows.reduce((s,r)=>s+(r.federalVotes||0),0),eligible=rows.reduce((s,r)=>s+r.eligible,0),sections=rows.filter(r=>r.checked||r.votes>0||(r.federalVotes||0)>0).length,totalSections=Math.max(rows.length,1),progress=Math.min(100,sections/totalSections*100);
 const previousElection=PREVIOUS_ELECTION_VOTES,achievement=Math.min(100,votes/previousElection*100),difference=votes-previousElection,projectedVotes=progress>0?Math.round(votes/(progress/100)):0;
 const normalize=(value:string)=>value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase();
 const camocimVotes=data.rows.filter(row=>normalize(row.municipality)==="camocim").reduce((sum,row)=>sum+row.votes,0);
 const victoryReached=camocimVotes>PREVIOUS_ELECTION_VOTES;
 function playVictorySound(){sendPlayerCommand("unMute");sendPlayerCommand("setVolume",[100]);sendPlayerCommand("playVideo")}
 function armVictorySound(){setSoundArmed(true);sendPlayerCommand("mute");sendPlayerCommand("playVideo");window.setTimeout(()=>{sendPlayerCommand("pauseVideo");sendPlayerCommand("unMute");if(victoryReached)playVictorySound()},700)}
 useEffect(()=>{if(victoryReached&&soundArmed&&playerReady)playVictorySound()},[victoryReached,soundArmed,playerReady]);
 const candidateTotals=(data.candidateMeta||[]).map(candidate=>({...candidate,votes:rows.reduce((sum,row)=>sum+(row.candidateVotes?.[candidate.key]||0),0)}));
 const ranking=Object.entries(rows.reduce<Record<string,number>>((a,r)=>{a[r.location]=(a[r.location]||0)+r.votes;return a},{})).sort((a,b)=>b[1]-a[1]).slice(0,5);
 return <main className="app-shell">
  <header className="topbar"><div className="brand"><span className="brand-mark">40</span><div><strong>APURAÇÃO 2026</strong><small>Sérgio Aguiar · Deputado Estadual</small></div></div><div className="status"><i/>Atualização automática<button onClick={refresh}><RefreshCw className={loading?"spin":""}/></button></div></header>
  <section className="toolbar"><div className="switch"><button className={mode==="interno"?"active":""} onClick={()=>setMode("interno")}><Database/>Apuração interna</button><button className={mode==="tse"?"active":""} onClick={()=>setMode("tse")}><ShieldCheck/>TSE oficial</button></div><label><MapPin/><select value={city} onChange={e=>setCity(e.target.value)}>{cities.map(c=><option key={c}>{c}</option>)}</select></label><button className={soundArmed?"sound-toggle active":"sound-toggle"} onClick={armVictorySound}><Volume2/>{soundArmed?"Som da vitória ativado":"Ativar som da vitória"}</button><button className="refresh" onClick={refresh}><RefreshCw/>Atualizar dados</button></section>
  <iframe ref={playerRef} onLoad={()=>setPlayerReady(true)} className="victory-player" title="Música da vitória" allow="autoplay; encrypted-media" src={`https://www.youtube.com/embed/${VICTORY_VIDEO_ID}?enablejsapi=1&playsinline=1&loop=1&playlist=${VICTORY_VIDEO_ID}`}/>
  {victoryReached&&<div className="victory-banner"><PartyPopper/><div><strong>Meta histórica superada!</strong><span>Sérgio chegou a {fmt.format(camocimVotes)} votos em Camocim e ultrapassou os {fmt.format(PREVIOUS_ELECTION_VOTES)} da última eleição.</span></div><button onClick={()=>{setSoundArmed(true);playVictorySound()}}><Volume2/>Tocar música</button></div>}
  {data.source==="demo"&&<div className="notice"><Clock3/><span><strong>Integração pronta para configurar.</strong> Os votos aparecerão assim que a URL de leitura for informada.</span></div>}
  <section className="hero">
   <article className="panel map-panel"><div className="heading"><div><span>CEARÁ · 184 MUNICÍPIOS</span><h1>Mapa da apuração</h1></div><a className="sheet-link" href="https://docs.google.com/spreadsheets/d/1LEDAYbRLuSSCVrUEnud_ONbY7-biZAzZ44ExAmmE_uc/edit?usp=sharing" target="_blank">Abrir planilha de entrada</a></div><div className="map-stage"><CearaMap rows={data.rows} selected={city} onSelect={setCity}/></div><section className="candidate-results map-candidates"><div className="heading"><div><span>APURAÇÃO DOS DEMAIS CANDIDATOS</span><h3>Estaduais e federais</h3></div><small>Atualização automática a cada 5 segundos</small></div><div className="candidate-grid">{candidateTotals.map(candidate=><article className={`candidate-result ${candidate.office.toLowerCase()}`} key={candidate.key}><span>{candidate.office}</span><b>{candidate.number}</b><h3>{candidate.name}</h3><strong>{fmt.format(candidate.votes)}</strong><small>votos</small></article>)}</div></section></article>
   <article className="panel summary"><div className="candidate"><b>40888</b><div><span>DEPUTADO ESTADUAL</span><h2>Sérgio Aguiar</h2><small>Resultado selecionado · Ceará</small></div></div><div className="total"><span>Total de votos</span><strong>{fmt.format(votes)}</strong><small>{mode==="tse"?"Fonte: resultados oficiais do TSE":"Fonte: planilha de apuração interna"}</small></div><div className="progress-label"><span>Urnas/seções com resultado</span><b>{sections} de {totalSections}</b></div><div className="progress"><i style={{width:`${progress}%`}}/></div><small>{progress.toFixed(2).replace(".",",")}% apurado</small><div className="projection-card"><div className="projection-title"><BarChart3/><span>PROJEÇÃO DE VOTOS</span></div><div className="projection-grid"><div><small>Última eleição</small><b>{fmt.format(previousElection)}</b></div><div><small>Projeção atual</small><b>{projectedVotes?fmt.format(projectedVotes):"—"}</b></div><div><small>Diferença</small><b className={difference>=0?"positive":"negative"}>{difference>=0?"+":""}{fmt.format(difference)}</b></div><div><small>Meta atingida</small><b>{achievement.toFixed(1).replace(".",",")}%</b></div></div><div className="projection-progress"><i style={{width:`${achievement}%`}}/></div></div><div className="federal-card"><div><span>DEPUTADO FEDERAL</span><h3>{(data.federalCandidate||"Deputado Federal").replace(/\./g,"")}</h3></div><strong>{fmt.format(federalVotes)}</strong><small>votos apurados</small></div><div className="metrics"><div><Vote/><span>Votos</span><b>{fmt.format(votes)}</b></div><div><CheckCircle2/><span>Aptos listados</span><b>{fmt.format(eligible)}</b></div><div><BarChart3/><span>Municípios</span><b>{new Set(rows.map(r=>r.municipality)).size}</b></div></div><div className="updated">Atualizado em {new Date(data.updatedAt).toLocaleString("pt-BR")}</div></article>
  </section>
  <section className="details"><article className="panel ranking"><div className="heading"><div><span>DESTAQUES</span><h3>Locais com mais votos</h3></div><BarChart3/></div>{ranking.filter(x=>x[1]>0).map(([n,v],i)=><div className="rank" key={n}><b>{i+1}</b><span>{n}</span><strong>{fmt.format(v)}</strong></div>)}{!ranking.some(x=>x[1]>0)&&<p className="empty">Os totais aparecerão conforme os dados forem inseridos.</p>}</article><article className="panel table-card"><div className="heading"><div><span>DETALHAMENTO</span><h3>Resultados por seção</h3></div><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar seção ou local"/></label></div><div className="table-scroll"><table><thead><tr><th>Seção</th><th>Local</th><th>Município</th><th>Estadual</th><th>Federal</th></tr></thead><tbody>{rows.map(r=><tr key={r.municipality+r.section}><td>{r.section}</td><td>{r.location}</td><td>{r.municipality}</td><td><b>{fmt.format(r.votes)}</b></td><td><b>{fmt.format(r.federalVotes||0)}</b></td></tr>)}</tbody></table></div></article></section>
  <footer><span>Painel eleitoral · Dados sujeitos à conferência</span><span>Desenvolvido por <b>Álefim Oliveira</b></span></footer>
 </main>
}
