"use client";
import { useEffect,useMemo,useState } from "react";
type Row=Record<string,string|number>;
const cargos={"Deputado Estadual":["SÉRGIO","ROMEU","EUVALDETE","OUTROS EST.","INDECISOS EST."],"Deputado Federal":["ROGER","TAYNA","OUTROS FED.","INDECISOS FED."],"Governador":["ELMANO","CIRO","OUTROS GOV.","INDECISOS GOV."]} as const;
export default function Dashboard(){
 const [rows,setRows]=useState<Row[]>([]);const [visitas,setVisitas]=useState<Row[]>([]);const [cargo,setCargo]=useState<keyof typeof cargos>("Deputado Estadual");const [candidato,setCandidato]=useState<string>("SÉRGIO");const [bairro,setBairro]=useState("Todos os bairros");const [loading,setLoading]=useState(true);const [erro,setErro]=useState("");const [updated,setUpdated]=useState("");
 async function carregar(){setLoading(true);setErro("");const r=await fetch("/api/data",{cache:"no-store"});if(r.status===401){location.replace("/");return}const j=await r.json();if(!r.ok)setErro(j.erro||"Não foi possível atualizar os dados.");else{setRows(j.rows||[]);setVisitas(j.visitas||[]);setUpdated(j.atualizadoEm)}setLoading(false)}
 useEffect(()=>{carregar();const timer=setInterval(carregar,60000);return()=>clearInterval(timer)},[]);useEffect(()=>{setCandidato(cargos[cargo][0])},[cargo]);
 const bairros=useMemo(()=>["Todos os bairros",...Array.from(new Set(rows.map(r=>String(r["BAIRRO/ÁREA"])))).sort()],[rows]);const filtered=useMemo(()=>bairro==="Todos os bairros"?rows:rows.filter(r=>r["BAIRRO/ÁREA"]===bairro),[rows,bairro]);
 const visitasFiltradas=useMemo(()=>bairro==="Todos os bairros"?visitas:visitas.filter(r=>r["BAIRRO/ÁREA"]===bairro),[visitas,bairro]);
 const ranking=useMemo(()=>filtered.map(r=>({bairro:String(r["BAIRRO/ÁREA"]),rua:String(r["RUA/LOCALIDADE"]),votos:Number(r[candidato]||0)})).filter(x=>x.votos>0).sort((a,b)=>b.votos-a.votos).slice(0,12),[filtered,candidato]);
 const totais=useMemo(()=>cargos[cargo].map(nome=>({nome,total:filtered.reduce((s,r)=>s+Number(r[nome]||0),0)})).sort((a,b)=>b.total-a.total),[filtered,cargo]);const votos=totais.reduce((s,x)=>s+x.total,0);const totalCandidato=filtered.reduce((s,r)=>s+Number(r[candidato]||0),0);const ruasComVoto=filtered.filter(r=>Number(r[candidato]||0)>0).length;const top=ranking[0];const max=Math.max(1,...ranking.map(x=>x.votos));const maxCandidate=Math.max(1,...totais.map(x=>x.total));
 const comparativo=useMemo(()=>[{nome:"Casas fechadas",campo1:"FECHADAS 1ª",campo2:"FECHADAS 2ª"},{nome:"Casas desabitadas",campo1:"DESAB. 1ª",campo2:"DESAB. 2ª"}].map(item=>{const primeira=visitasFiltradas.reduce((s,r)=>s+Number(r[item.campo1]||0),0);const segunda=visitasFiltradas.reduce((s,r)=>s+Number(r[item.campo2]||0),0);return{nome:item.nome,primeira,segunda,diferenca:segunda-primeira,variacao:primeira?((segunda-primeira)/primeira)*100:segunda?100:0}}),[visitasFiltradas]);
 const primeiraVisita=comparativo.reduce((s,x)=>s+x.primeira,0);const segundaVisita=comparativo.reduce((s,x)=>s+x.segunda,0);const diferencaVisitas=segundaVisita-primeiraVisita;const variacaoVisitas=primeiraVisita?diferencaVisitas/primeiraVisita*100:segundaVisita?100:0;
 async function sair(){await fetch("/api/logout",{method:"POST"});location.replace("/")}
 function emitirRelatorio(){
  const janela=window.open("","_blank");if(!janela)return alert("Permita a abertura de pop-ups para emitir o relatório.");janela.opener=null;
  const safe=(value:unknown)=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]||char));
  const data=new Date().toLocaleString("pt-BR");
  const linhasRanking=ranking.length?ranking.map((x,i)=>`<tr><td>${i+1}</td><td>${safe(x.rua)}</td><td>${safe(x.bairro)}</td><td class="numero">${x.votos.toLocaleString("pt-BR")}</td></tr>`).join(""):`<tr><td colspan="4" class="vazio">Sem votos lançados para o filtro selecionado.</td></tr>`;
  const linhasCandidatos=totais.map(x=>`<tr><td>${safe(x.nome)}</td><td class="numero">${x.total.toLocaleString("pt-BR")}</td></tr>`).join("");
  const linhasComparativo=comparativo.map(x=>`<tr><td>${safe(x.nome)}</td><td class="numero">${x.primeira.toLocaleString("pt-BR")}</td><td class="numero">${x.segunda.toLocaleString("pt-BR")}</td><td class="numero ${x.diferenca>=0?"positivo":"negativo"}">${x.diferenca>=0?"+":""}${x.diferenca.toLocaleString("pt-BR")}</td><td class="numero">${x.variacao.toLocaleString("pt-BR",{maximumFractionDigits:1})}%</td></tr>`).join("");
  janela.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Relatório - ${safe(candidato)}</title><style>
   *{box-sizing:border-box}body{margin:0;padding:38px;color:#172033;font-family:Arial,sans-serif;background:#fff}.faixa{height:8px;background:linear-gradient(90deg,#e51b2a 0 25%,#ffd500 25% 50%,#009b4e 50% 75%,#0072bc 75%);margin:-38px -38px 32px}.cabecalho{display:flex;justify-content:space-between;gap:24px;border-bottom:2px solid #e51b2a;padding-bottom:18px}.marca{display:flex;gap:14px;align-items:center}.numero40{width:52px;height:52px;border-radius:14px;display:grid;place-items:center;background:#e51b2a;color:#fff;font-size:20px;font-weight:900}.cabecalho h1{margin:0 0 5px;color:#143968;font-family:Georgia,serif;font-size:27px}.cabecalho p,.emissao{margin:0;color:#687487;font-size:11px}.emissao{text-align:right}.filtros{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:22px 0}.filtro,.metrica{border:1px solid #e5e8ed;border-radius:10px;padding:11px}.filtro span,.metrica span{display:block;color:#7b8494;font-size:9px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.filtro strong{display:block;margin-top:5px;font-size:12px}.metricas{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:24px}.metrica strong{display:block;margin-top:5px;color:#143968;font-family:Georgia,serif;font-size:21px}.grid{display:grid;grid-template-columns:1.4fr 1fr;gap:18px}.bloco{break-inside:avoid;margin-bottom:22px}.bloco h2{color:#143968;font-size:15px;margin:0 0 9px}table{width:100%;border-collapse:collapse;font-size:11px}th{background:#f3f5f7;color:#687487;text-align:left;font-size:9px;letter-spacing:.05em;text-transform:uppercase}th,td{border-bottom:1px solid #e9ebef;padding:8px}.numero{text-align:right;font-weight:800}.positivo{color:#008546}.negativo{color:#c91422}.vazio{text-align:center;color:#7b8494;padding:24px}.rodape{margin-top:28px;padding-top:12px;border-top:1px solid #e5e8ed;color:#8a93a1;font-size:9px;text-align:center}.acoes{display:flex;justify-content:flex-end;margin-bottom:18px}.imprimir{border:0;border-radius:9px;background:#e51b2a;color:#fff;padding:10px 15px;font-weight:800;cursor:pointer}@media print{body{padding:20px}.faixa{margin:-20px -20px 25px}.acoes{display:none}}@media(max-width:700px){body{padding:20px}.faixa{margin:-20px -20px 24px}.filtros,.metricas,.grid{grid-template-columns:1fr 1fr}.cabecalho{flex-direction:column}.emissao{text-align:left}}
  </style></head><body><div class="faixa"></div><div class="acoes"><button class="imprimir" onclick="window.print()">Imprimir / Salvar em PDF</button></div><header class="cabecalho"><div class="marca"><div class="numero40">40</div><div><h1>Relatório territorial</h1><p>Comitê Sérgio Aguiar • Pesquisa 2026</p></div></div><div class="emissao">Emitido em<br><strong>${safe(data)}</strong></div></header><section class="filtros"><div class="filtro"><span>Cargo</span><strong>${safe(cargo)}</strong></div><div class="filtro"><span>Candidato</span><strong>${safe(candidato)}</strong></div><div class="filtro"><span>Bairro / Área</span><strong>${safe(bairro)}</strong></div></section><section class="metricas"><div class="metrica"><span>Votos no cargo</span><strong>${votos.toLocaleString("pt-BR")}</strong></div><div class="metrica"><span>Votos do candidato</span><strong>${totalCandidato.toLocaleString("pt-BR")}</strong></div><div class="metrica"><span>Ruas com votos</span><strong>${ruasComVoto}</strong></div><div class="metrica"><span>Rua mais votada</span><strong>${top?.votos??0}</strong></div></section><div class="bloco"><h2>Comparativo — 1ª visita × 2ª visita</h2><table><thead><tr><th>Candidato</th><th class="numero">1ª visita</th><th class="numero">2ª visita</th><th class="numero">Diferença</th><th class="numero">Variação</th></tr></thead><tbody>${linhasComparativo}</tbody></table></div><section class="grid"><div class="bloco"><h2>Ranking de ruas — ${safe(candidato)}</h2><table><thead><tr><th>#</th><th>Rua / Localidade</th><th>Bairro / Área</th><th class="numero">Votos</th></tr></thead><tbody>${linhasRanking}</tbody></table></div><div class="bloco"><h2>Comparativo de candidatos</h2><table><thead><tr><th>Candidato</th><th class="numero">Votos</th></tr></thead><tbody>${linhasCandidatos}</tbody></table></div></section><footer class="rodape">Painel de Planilhas — Comitê Sérgio Aguiar • Dados gerados conforme os filtros selecionados</footer></body></html>`);
  janela.document.close();
 }
 return <main className="dashboard-shell"><header className="topbar"><div className="top-brand"><div className="mini-crest">40</div><div className="top-title"><strong>Painel de Planilhas</strong><span>COMITÊ SÉRGIO AGUIAR • 2026</span></div></div><div className="top-actions"><span className="user-chip">Administrador</span><button className="logout-button" onClick={sair}>Sair ↗</button></div></header><div className="dashboard-main">
  <div className="dashboard-heading"><div><span className="eyebrow">VISÃO TERRITORIAL</span><h1>Resultados por rua</h1></div><div><span className="live">Dados conectados</span><p className="updated">{updated?`Atualizado às ${new Date(updated).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}`:"Carregando atualização…"}</p></div></div>
  <section className="filters"><label>CARGO<select value={cargo} onChange={e=>setCargo(e.target.value as keyof typeof cargos)}>{Object.keys(cargos).map(x=><option key={x}>{x}</option>)}</select></label><label>CANDIDATO<select value={candidato} onChange={e=>setCandidato(e.target.value)}>{cargos[cargo].map(x=><option key={x}>{x}</option>)}</select></label><label>BAIRRO / ÁREA<select value={bairro} onChange={e=>setBairro(e.target.value)}>{bairros.map(x=><option key={x}>{x}</option>)}</select></label><button type="button" className="report-button" onClick={emitirRelatorio} disabled={loading||!!erro}>▤ Emitir relatório</button><button type="button" className="refresh-button" onClick={carregar} disabled={loading}>↻ {loading?"Atualizando":"Atualizar"}</button></section>
  {erro?<div className="error-state">{erro}. Verifique se a planilha está compartilhada para leitura por link.</div>:<><section className="metrics"><article className="metric-card"><span className="metric-label">Votos no cargo</span><strong className="metric-value">{votos.toLocaleString("pt-BR")}</strong><div className="metric-detail">{cargo}</div></article><article className="metric-card"><span className="metric-label">Votos do candidato</span><strong className="metric-value">{totalCandidato.toLocaleString("pt-BR")}</strong><div className="metric-detail">{candidato}</div></article><article className="metric-card"><span className="metric-label">Ruas com votos</span><strong className="metric-value">{ruasComVoto}</strong><div className="metric-detail">de {filtered.length} ruas analisadas</div></article><article className="metric-card"><span className="metric-label">Rua mais votada</span><strong className="metric-value">{top?.votos??0}</strong><div className="metric-detail">{top?.rua??"Sem votos lançados"}</div></article></section>
  <section className="visit-comparison panel"><div className="panel-head"><div><h2>Comparativo — 1ª visita × 2ª visita</h2><div className="panel-kicker">Dados consolidados da guia RESUMO POR BAIRRO</div></div><span className={`visit-delta ${diferencaVisitas>=0?"up":"down"}`}>{diferencaVisitas>=0?"+":""}{diferencaVisitas} ocorrências</span></div><div className="visit-summary"><div><span>1ª VISITA</span><strong>{primeiraVisita.toLocaleString("pt-BR")}</strong></div><div className="visit-arrow">→</div><div><span>2ª VISITA</span><strong>{segundaVisita.toLocaleString("pt-BR")}</strong></div><div><span>VARIAÇÃO</span><strong>{variacaoVisitas.toLocaleString("pt-BR",{maximumFractionDigits:1})}%</strong></div></div><div className="visit-table"><div className="visit-table-head"><span>Indicador</span><span>1ª visita</span><span>2ª visita</span><span>Diferença</span></div>{comparativo.map(x=><div className="visit-table-row" key={x.nome}><strong>{x.nome}</strong><span>{x.primeira}</span><span>{x.segunda}</span><span className={x.diferenca>=0?"up":"down"}>{x.diferenca>=0?"+":""}{x.diferenca}</span></div>)}</div></section>
  <section className="dashboard-grid"><article className="panel"><div className="panel-head"><div><h2>Ranking de ruas — {candidato}</h2><div className="panel-kicker">Ordenado pelo maior número de votos</div></div><span className="updated">TOP 12</span></div>{ranking.length?<div className="rank-list">{ranking.map((x,i)=><div className="rank-row" key={`${x.bairro}-${x.rua}`}><span className="rank-number">{String(i+1).padStart(2,"0")}</span><div className="rank-name"><strong>{x.rua}</strong><span>{x.bairro}</span></div><div className="bar-track"><div className="bar" style={{width:`${x.votos/max*100}%`}}/></div><span className="rank-votes">{x.votos}</span></div>)}</div>:<div className="empty-state">Ainda não há votos lançados para este candidato no filtro selecionado.</div>}</article><article className="panel"><div className="panel-head"><div><h2>Comparativo de candidatos</h2><div className="panel-kicker">Total no filtro atual</div></div></div><div className="candidate-list">{totais.map(x=><div className="candidate-row" key={x.nome}><div className="candidate-top"><strong>{x.nome}</strong><span>{x.total} votos</span></div><div className="candidate-bar"><div className="candidate-fill" style={{width:`${x.total/maxCandidate*100}%`}}/></div></div>)}</div></article></section></>}
  <footer className="dashboard-footer"><span>© 2026 Todos os direitos reservados.</span><span>Desenvolvedor: <strong>Álefim Oliveira</strong></span></footer>
 </div></main>
}
