"use client";
import { useEffect,useMemo,useState } from "react";
type Row=Record<string,string|number>;
const cargos={"Deputado Estadual":["SÉRGIO","ROMEU","EUVALDETE","OUTROS EST.","INDECISOS EST."],"Deputado Federal":["ROGER","TAYNA","OUTROS FED.","INDECISOS FED."],"Governador":["ELMANO","CIRO","OUTROS GOV.","INDECISOS GOV."]} as const;
export default function Dashboard(){
 const [rows,setRows]=useState<Row[]>([]);const [cargo,setCargo]=useState<keyof typeof cargos>("Deputado Estadual");const [candidato,setCandidato]=useState<string>("SÉRGIO");const [bairro,setBairro]=useState("Todos os bairros");const [loading,setLoading]=useState(true);const [erro,setErro]=useState("");const [updated,setUpdated]=useState("");
 async function carregar(){setLoading(true);setErro("");const r=await fetch("/api/data",{cache:"no-store"});if(r.status===401){location.replace("/");return}const j=await r.json();if(!r.ok)setErro(j.erro||"Não foi possível atualizar os dados.");else{setRows(j.rows||[]);setUpdated(j.atualizadoEm)}setLoading(false)}
 useEffect(()=>{carregar();const timer=setInterval(carregar,60000);return()=>clearInterval(timer)},[]);useEffect(()=>{setCandidato(cargos[cargo][0])},[cargo]);
 const bairros=useMemo(()=>["Todos os bairros",...Array.from(new Set(rows.map(r=>String(r["BAIRRO/ÁREA"])))).sort()],[rows]);const filtered=useMemo(()=>bairro==="Todos os bairros"?rows:rows.filter(r=>r["BAIRRO/ÁREA"]===bairro),[rows,bairro]);
 const ranking=useMemo(()=>filtered.map(r=>({bairro:String(r["BAIRRO/ÁREA"]),rua:String(r["RUA/LOCALIDADE"]),votos:Number(r[candidato]||0)})).filter(x=>x.votos>0).sort((a,b)=>b.votos-a.votos).slice(0,12),[filtered,candidato]);
 const totais=useMemo(()=>cargos[cargo].map(nome=>({nome,total:filtered.reduce((s,r)=>s+Number(r[nome]||0),0)})).sort((a,b)=>b.total-a.total),[filtered,cargo]);const votos=totais.reduce((s,x)=>s+x.total,0);const totalCandidato=filtered.reduce((s,r)=>s+Number(r[candidato]||0),0);const ruasComVoto=filtered.filter(r=>Number(r[candidato]||0)>0).length;const top=ranking[0];const max=Math.max(1,...ranking.map(x=>x.votos));const maxCandidate=Math.max(1,...totais.map(x=>x.total));
 async function sair(){await fetch("/api/logout",{method:"POST"});location.replace("/")}
 return <main className="dashboard-shell"><header className="topbar"><div className="top-brand"><div className="mini-crest">40</div><div className="top-title"><strong>Painel de Planilhas</strong><span>COMITÊ SÉRGIO AGUIAR • 2026</span></div></div><div className="top-actions"><span className="user-chip">Administrador</span><button className="logout-button" onClick={sair}>Sair ↗</button></div></header><div className="dashboard-main">
  <div className="dashboard-heading"><div><span className="eyebrow">VISÃO TERRITORIAL</span><h1>Resultados por rua</h1></div><div><span className="live">Dados conectados</span><p className="updated">{updated?`Atualizado às ${new Date(updated).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}`:"Carregando atualização…"}</p></div></div>
  <section className="filters"><label>CARGO<select value={cargo} onChange={e=>setCargo(e.target.value as keyof typeof cargos)}>{Object.keys(cargos).map(x=><option key={x}>{x}</option>)}</select></label><label>CANDIDATO<select value={candidato} onChange={e=>setCandidato(e.target.value)}>{cargos[cargo].map(x=><option key={x}>{x}</option>)}</select></label><label>BAIRRO / ÁREA<select value={bairro} onChange={e=>setBairro(e.target.value)}>{bairros.map(x=><option key={x}>{x}</option>)}</select></label><button className="refresh-button" onClick={carregar} disabled={loading}>↻ {loading?"Atualizando":"Atualizar"}</button></section>
  {erro?<div className="error-state">{erro}. Verifique se a planilha está compartilhada para leitura por link.</div>:<><section className="metrics"><article className="metric-card"><span className="metric-label">Votos no cargo</span><strong className="metric-value">{votos.toLocaleString("pt-BR")}</strong><div className="metric-detail">{cargo}</div></article><article className="metric-card"><span className="metric-label">Votos do candidato</span><strong className="metric-value">{totalCandidato.toLocaleString("pt-BR")}</strong><div className="metric-detail">{candidato}</div></article><article className="metric-card"><span className="metric-label">Ruas com votos</span><strong className="metric-value">{ruasComVoto}</strong><div className="metric-detail">de {filtered.length} ruas analisadas</div></article><article className="metric-card"><span className="metric-label">Rua mais votada</span><strong className="metric-value">{top?.votos??0}</strong><div className="metric-detail">{top?.rua??"Sem votos lançados"}</div></article></section>
  <section className="dashboard-grid"><article className="panel"><div className="panel-head"><div><h2>Ranking de ruas — {candidato}</h2><div className="panel-kicker">Ordenado pelo maior número de votos</div></div><span className="updated">TOP 12</span></div>{ranking.length?<div className="rank-list">{ranking.map((x,i)=><div className="rank-row" key={`${x.bairro}-${x.rua}`}><span className="rank-number">{String(i+1).padStart(2,"0")}</span><div className="rank-name"><strong>{x.rua}</strong><span>{x.bairro}</span></div><div className="bar-track"><div className="bar" style={{width:`${x.votos/max*100}%`}}/></div><span className="rank-votes">{x.votos}</span></div>)}</div>:<div className="empty-state">Ainda não há votos lançados para este candidato no filtro selecionado.</div>}</article><article className="panel"><div className="panel-head"><div><h2>Comparativo de candidatos</h2><div className="panel-kicker">Total no filtro atual</div></div></div><div className="candidate-list">{totais.map(x=><div className="candidate-row" key={x.nome}><div className="candidate-top"><strong>{x.nome}</strong><span>{x.total} votos</span></div><div className="candidate-bar"><div className="candidate-fill" style={{width:`${x.total/maxCandidate*100}%`}}/></div></div>)}</div></article></section></>}
 </div></main>
}
